version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - mvn package
      - aws cloudformation package --template-file sam.yaml --output-template-file output-sam.yaml --s3-bucket ${DeployBucket}
artifacts:
  files:
    - 'busqandote-scraper-1.0-SNAPSHOT-lambda-package.zip'
    - 'output-sam.yaml'
  discard-paths: yes