AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.busqandote::busqandote-scraper

Resources:
  ScraperRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
        Effect: Allow
        Principal:
          Service:
          - lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Type: AWS::IAM::Role

  BusqandoteScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.busqandote.Application::handleRequest
      Runtime: java8
      CodeUri: target/busqandote-scraper-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 256
      Timeout: 30
      Role: !GetAtt ScraperRole.Arn
      Events:
        Testy:
          Properties:
            Schedule: rate(10 minutes)
          Type: Schedule
